name:                Heckin
version:             0.0.1.0
github:              "maxdeviant/heckin"
license:             MIT
author:              "Marshall Bowers"
maintainer:          "elliott.codes@gmail.com"
copyright:           "2019 Marshall Bowers"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
synopsis:            Oh heck, it's a heckin' case conversion library.
category:            Data, Text

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/maxdeviant/heckin#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

tests:
  Heckin-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Heckin
    - hspec
